### ISSUE TITLE
Thankyou for this tool, please could advise on XR_ERROR_RUNTIME_FAILURE

### ISSUE THREAD

**Issue by evanswillo** [maluoi/openxr-explorer#6]
After a fresh Windows 11 install  and WMR App install I see the following message xrCreateSession error XR_ERROR_RUNTIME_FAILURE, is there an explanation or further debug I can look at. 
![Screenshot 2022-01-07 180929](https://user-images.githubusercontent.com/87306955/148587738-0b2eb0d8-ad1b-476f-ab66-4e30302cea2b.png)
Regard
Richard

**Comment by RocketTree** [comment]
I am having the same issue on windows 10 with runtime version 108.211.23004

Interestingly the OpenXR Developer Tools for Windows Mixed Reality Demo Scene loads and runs correctly, so creating a XrSession seems possible.  But my own code calling xrCreateSession gets the same XR_ERROR_RUNTIME_FAILURE result.

If I change the runtime to SteamVR everything works correctly, so I think this specifically a WMR issue.

**Comment by evanswillo** [comment]
HI, thanks for taking the time to look at this.   I agree with your findings the STEAMVR runtime  does not display the same error message.  The reason I am looking at this issue is because when I use another utility that load in a OpenXR API Layer for NVIDIA Image Scaling (NIS), then although the API Layer appears to function in the OpenXR Dev Tool I was seeing two error messages,
Home Tab it is saying XrResult failure [XR_ERRO  _FILE_ACCESS_ERROR]
Origin: xrCreateInstance(&createInfo,instance.Put())
System Status Tab
Unknown OpenXR Runtime
Runtime manifest C:\WINDOWS\system32\MixedRealityRuntime.json
Exception XrResult failure [XR_ERROR_FILE_ACCESS_ERROR]
Origin: xrCreateInstance(&createInfo,instance.Put()) 

What is typically strange after days of investigation the error message in OPENXR Explorer remains but the issue in OPENXR Developer seems to have corrected itself.

The only change I have make was to install steamvr, maybe the toggle between these two OPENXR runtimes has somehow  fixed the issue that caused the errors in the OPENXR Developer tool .

But would still like to understand the error in OPENXR Explorer

Regards Richard

**Comment by RocketTree** [comment]
I have posted this over on the Khronos OpenXR forums as I think it may get a better answer from there.  I think this is a Microsoft problem, not specifically an issue with this application.  I can't seem to find any Microsoft OpenXR specific forum to post this issue to, but perhaps the developer of this tool may know where to direct such questions.

**Comment by mbucchia-msft** [comment]
Just seeing this now. @evanswillo and @RocketTree, if you are using my NIS tool, this is likely the issue of when it's not installed in the default folder.

https://github.com/mbucchia/XR_APILAYER_NOVENDOR_nis_scaler/issues/9

This issue is resolved in the next version of the NIS tool.

This is not an issue of the OpenXR Explorer.

**Comment by RocketTree** [comment]
Hi,  I am not using the NIS tool or the OpenXr Toolkit.  So there may be some underlying issue with WMR OpenXR implementation.  I agree this is not an issue with OpenXR Explorer.  
I have submitted this as a bug to via the Windows Feedback hub

**Comment by Jabbah** [comment]
Hi @RocketTree, did you get any updates from MS on this? I'm working on getting OpenComposite-OpenXR working for a few games and run into this issue on a couple of games but not others. OpenExplorer also has the runtime failure for me, so possibly these are related. As OpenComposite is working for one game and not another (which then works with SteamVR's OpenXR runtime), it might be something to do with how D3D is being setup or some other initialisation that is incompatible with MS's OpenXR runtime.

**Comment by RocketTree** [comment]
Hi @Jabbah, I have not had any update from MS.  I had thought it could be D3D related but didn't notice anything different between the samples which work and our engine.  I will check again because I could have missed something.

Our D3D11 codebase works on SteamVR and Oculus VR (Quest 2 via airlink) but still nothing on direct WMR.  

Are any of the games you are testing on open source?  It would be good to look through any working or not working codebases to try and find some possible differences.

**Comment by mbucchia-msft** [comment]
@RocketTree and @Jabbah, I've replied on the Khronos forum here: https://community.khronos.org/t/xrcreatesession-returning-xr-error-runtime-failure-for-windows-mixed-reality/108165/8

Please take a look.

I think meanwhile you should close the issue on this project, since the failure is likely not related to @maluoi's OpenXR Explorer.

Thanks!
